name: mishtu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker:
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: arianaVioleta
      fonts:
        - asset: assets/font/arianaVioleta.ttf
    - family: morganChalk
      fonts:
        - asset: assets/font/morganChalk.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/font/Raleway-SemiBold.ttf
    - family: Avengeance
      fonts:
        - asset: assets/font/Avengeance.otf

  assets:
    - assets/images/
    - assets/images/avatarfolder/
    - assets/font/



